{{ $fullName := include "etoro.fullname" . }}
{{ $port := .Values.service.port }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadate:
  name: {{ include "etoro.fullname" . }}
  labels:
    {{ include "etoro.labels" . | nindent 4 }}
  {{ with .Values.ingress.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
  {{ end }}
  spec:
    rules: 
      {{ range .Values.ingress.hosts }}
        - host: {{ .host | quote }}
          http:
            paths:
              - path: {{ .path }}
                backend:
                  serviceName: {{ $fullName }}
                  servicePort: {{ $port }}
      {{ end }}
